version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/ruby:2.7.4-node'
    resource_class: brianoh1979/brian-containeragent2
    steps:
      - checkout
      - run: sudo apt-get update
      - run: bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
   
  test:
    docker:
      - image: 'cimg/ruby:2.7.4-node'
      - environment:
          POSTGRES_DB: rails_blog_test
          POSTGRES_PASSWORD: ''
          POSTGRES_USER: circleci-demo-ruby
        image: 'circleci/postgres:9.5-alpine'
    environment:
      BUNDLE_JOBS: '3'
      BUNDLE_RETRY: '3'
      PGHOST: 127.0.0.1
      PGPASSWORD: ''
      PGUSER: circleci-demo-ruby
      RAILS_ENV: test
    parallelism: 3
    resource_class: brianoh1979/brian-containeragent2
    steps:
      - checkout
      - run: sudo apt-get update
      - run: gem install rake
      - run: bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
      - run: rake db:create && rake db:migrate
      - run:
          command: 'dockerize -wait tcp://localhost:5432 -timeout 1m'
          name: Wait for DB
      - run:
          command: 'bundle exec rails db:schema:load --trace'
          name: Database setup
      - run: mkdir -p /tmp/test-results/rspec
      - run: TESTFILES=$(circleci-agent tests glob "spec/**/*_spec.rb" | circleci-agent tests split --split-by=timings)
      - run: bundle exec rspec $TESTFILES --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec/results.xml --format progress
  #    - ruby/rspec-test
      - ruby/rubocop-check


  deploy:
    docker:
      - image: 'cimg/ruby:2.7.4-node'
    resource_class: brianoh1979/brian-containeragent2
    steps:
      - checkout
      - run: sudo apt-get update
      - run: bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java
      - ruby/install-deps
      - heroku/install
      - heroku/deploy-via-git
          force: true
orbs:
  path-filtering: circleci/path-filtering@0.1.1
  ruby: circleci/ruby@1.1.4
  node: circleci/node@2
  heroku: circleci/heroku@1.2.6
  cypress: cypress-io/cypress@1.29.0
  docker: circleci/docker@2.1.4
executors:
  ruby:
    docker:
      - image: 'cimg/ruby:2.7.4-node'
    resource_class: brianoh1979/brian-containeragent2

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - cypress/install:
          cache-key: 'cache2-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}'
      - cypress/run:
          build: bundle install && sudo apt-get update && sudo apt-get install xvfb libgtk-3-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 --fix-missing
          executor: ruby 
          start: cd ~/project && rails server
          wait-on: http://localhost:3000
          cache-key: 'cache2-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}'
          requires:
            - cypress/install
          attach-workspace: yes
      - hold:
         type: approval
         requires:
           - test
           - cypress/run
      - deploy:
          requires:
            - hold

         
