version: 2.1

jobs:
 build:
   docker:
     - image: cimg/base:2021.11
   steps:
     - run: echo "Hi I'm on a CircleCIs hosted compute!"
 
 test:
   docker:
     - image: cimg/base:2021.11
   steps:
     - run: echo "Hi I'm on a CircleCIs hosted compute!"
 
 deploy-to-eks:
   docker:
     - image: cimg/base:2021.11
   resource_class: db-cci-ns/terraform-module
   steps:
     - run:  echo "Hi I'm on a container runner!"
  
 deploy-to-ecs:
   docker:
     - image: cimg/base:2021.11
   resource_class: db-cci-ns/terraform-module
   steps:
     - run:  echo "Hi I'm on a container runner!"

 internal-security-scan:
   docker:
     - image: cimg/base:2021.11
   resource_class: db-cci-ns/terraform-module
   steps:
     - run:  echo "Hi I'm on a container runner!"

workflows:
 main-workflow:
   jobs:
    - build
    - test:
        requires:
         - build
    - internal-security-scan:
        requires:
         - test
    - deploy-to-eks:
        requires:
         - internal-security-scan
    - deploy-to-ecs:
        requires:
         - internal-security-scan

